import{a as F,S as b,i as l}from"./assets/vendor-D0cagnvz.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const g=async(o,a=1,r=15)=>{const e={key:"47393342-0b139bb531c328d079618af8b",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:r};try{return(await F.get("https://pixabay.com/api/",{params:e})).data}catch(t){return console.error("Failed to fetch photos:",t.message),{hits:[],totalHits:0}}},y=o=>o.map(({webformatURL:a,largeImageURL:r,tags:s,likes:e,views:t,comments:i,downloads:f})=>`<li class="gallery-item" >
            <a href="${r}" alt="${s}" title=""/>
            <img src="${a}" alt="${s}" class="gallery-image">
            <div class="gallery-container">
            <p class="item"><span class="item-text">Likes</span> <span>${e}</span></p>
            <p class="item"><span class="item-text">Wiews</span> <span>${t}</span></p>
            <p class="item"><span class="item-text">Comments</span> <span>${i}</span></p>
            <p class="item"><span class="item-text">Downlods</span> <span>${f}</span></p>
            </div></a>
            </li>`).join("");let u=new b(".gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250}),p=1,h="",c=0;const E=document.getElementById("search-form"),m=document.getElementById("gallery"),d=document.querySelector(".loader"),n=document.querySelector(".load-button");n.style.display="none";E.addEventListener("submit",async o=>{o.preventDefault();const r=document.getElementById("search-input").value.trim();if(!r){l.info({title:"",message:"Please, enter a search term!",messageColor:"#FAFAFB",backgroundColor:"#EF4040",position:"topRight"});return}h=r,p=1,c=0,m.innerHTML="",d.style.display="block",n.style.display="none";try{const s=await g(r,p),e=s.hits,t=s.totalHits;e.length?(c+=e.length,m.innerHTML=y(e),u.refresh(),c<t?n.style.display="block":n.style.display="none"):l.info({title:"",backgroundColor:"#EF4040",messageColor:"#FAFAFB",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}catch(s){console.error("Error fetching data:",s),l.error({title:"Error",message:"Something went wrong. Please try again later.",messageColor:"#FAFAFB",backgroundColor:"#EF4040",position:"topRight"})}finally{d.style.display="none"}});n.addEventListener("click",async()=>{p+=1,d.style.display="block";try{const o=await g(h,p);o.hits.length&&(c+=o.hits.length,m.innerHTML+=y(o.hits),u.refresh(),window.scrollBy({top:570,behavior:"smooth"}),c>=o.totalHits&&(n.style.display="none",l.info({message:"We`re sorry, but you`ve reached the end of search results.",messageColor:"#FAFAFB",backgroundColor:"#91A9FF",position:"topRight"})))}catch(o){console.error("Error loading more photos:",o),l.error({message:"Failed to load more images. Please try again later.",messageColor:"#FAFAFB",backgroundColor:"#EF4040",position:"topRight"})}finally{d.style.display="none"}});
//# sourceMappingURL=index.js.map
